### ISSUE TITLE
Fix this issue

### ISSUE THREAD

**Issue by ghost** [di72nn/callrecorder-axet#11]
![IMG_20210523_110248](https://user-images.githubusercontent.com/84654865/119249477-7073a080-bbb6-11eb-85f2-ced9e6a9c995.jpg)
![Screenshot_2021-05-23-11-03-37-82](https://user-images.githubusercontent.com/84654865/119249491-8ed99c00-bbb6-11eb-8c68-2bfaafa0cc33.jpg)
Fix this problem app after every reboot,app is closed and recording eror 0000 loading animation  and add auto start after boot complete.

**Comment by di72nn** [comment]
Not an issue with the Magisk module, [deal with the app](https://gitlab.com/axet/android-call-recorder).
