### ISSUE TITLE
STUCK AT MIUI LOGO AFTER UNINSTALL!!!!!!!

### ISSUE THREAD

**Issue by BahadirKaya90** [di72nn/callrecorder-axet#12]
I installed the app on my POCO F2 PRO with magisk module! Later I unistalled it and clicked reboot the phone button!!! The phone remained on the MIUI Screen!!!! How will I save my phone now!!!!!

**Comment by di72nn** [comment]
Did you use root **in the app** to enable "System Mixer Incall Recording"?

**Comment by BahadirKaya90** [comment]
> Did you use root **in the app** to enable "System Mixer Incall Recording"?

Yes I had used it.

**Comment by di72nn** [comment]
[The instructions](https://github.com/di72nn/callrecorder-axet#how-to-use) said not to do it. It is [known](https://gitlab.com/axet/android-call-recorder/-/issues/160) to be dangerous.
Now you have to reinstall MIUI. There is plenty of material on that online.

**Comment by xDonatello** [comment]
I too went in bootloop!

**Comment by xDonatello** [comment]
> [The instructions](https://github.com/di72nn/callrecorder-axet#how-to-use) said not to do it. It is [known](https://gitlab.com/axet/android-call-recorder/-/issues/160) to be dangerous.
> Now you have to reinstall MIUI. There is plenty of material on that online.

You have not written this in the instructions

**Comment by di72nn** [comment]
@xDonatello re-read the third point in the "How to use" section.

**Comment by di72nn** [comment]
BTW, you **don't have to** reinstall MIUI - you may try restoring `/etc/mixer_paths*.xml` some other way.

**Comment by xDonatello** [comment]
> @xDonatello re-read the third point in the "How to use" section.

The third point is ambiguous
