### ISSUE TITLE
No autostart on Android 11

### ISSUE THREAD

**Issue by rustyx** [di72nn/callrecorder-axet#14]
On Mi 11 (Android 11 MIUI 12.5) the app works after starting manually, but displays a warning "the app never received the BOOT event". And there's no "allow autostart" setting for this app. Could it be that some permission is missing in the manifest (either app or priv)?

**Comment by di72nn** [comment]
Probably an app/ROM issue, not related to the Magisk module. Try [the app repo](https://gitlab.com/axet/android-call-recorder/-/issues).

If there's a system permission that can help, I can add it to the module, but only after it's tested.

**Comment by rustyx** [comment]
If you're not sure, why close the issue?

**Comment by di72nn** [comment]
Because I'm sure enough.

At this point this module has nothing to do with startup permissions and there is no reason assume that only system-level permissions can help with this.
