### ISSUE TITLE
Start on boot pixel 6

### ISSUE THREAD

**Issue by lavoie005** [di72nn/callrecorder-axet#15]
Hi, on my pixel 6 root with magisk 24102, your app doesnt start au boot.
If you dont start it manually your phone call isnt recorde, anything we can do?
Android 12

**Comment by di72nn** [comment]
Hi, sorry for a late reply.
Create an issue in [the app repo](https://gitlab.com/axet/android-call-recorder). The Magisk module doesn't deal with startup.
