### ISSUE TITLE
Xiaomi mi 11 Pro - Option: System Mixer Incall Recording - can't be enabled?

### ISSUE THREAD

**Issue by Hot12345** [di72nn/callrecorder-axet#19]
Hi, 

Im getting the following error on:
Option: System Mixer Incall Recording - can't be enabled 
Pops the following error: https://imgur.com/2V84mmm

What does this setting and how can I fix this?

**Comment by di72nn** [comment]
This option does a modification to a system configuration file. The whole purpose of this Magisk module to avoid such modifications. If you really think you need to enable it, please refer to [the app repo](https://gitlab.com/axet/android-call-recorder) for details and support.
