### ISSUE TITLE
VOIP Calls (Signal, WTFapp etc.) not recording ....! Is that possible?

### ISSUE THREAD

**Issue by mr-gittes** [di72nn/callrecorder-axet#2]

**Comment by di72nn** [comment]
Wrong repo.
[Ability to record from other apps such as Whatsapp, Viber, etc.](https://gitlab.com/axet/android-call-recorder/-/issues/131).
[WhatsApp Call Recording](https://gitlab.com/axet/android-call-recorder/-/issues/152).
