### ISSUE TITLE
Using without root

### ISSUE THREAD

**Issue by humarci** [di72nn/callrecorder-axet#20]
Can I use this module without root? With magisk the module tab is not active when my phone is not rooted.
Is there other way (maybe via recovery mode or on Xiaomi phones with the fastboot mode) to inject this code into my system?
I tried on Android 13 (Evolution X 7.5 ROM) with the latest magisk.

**Comment by Hot12345** [comment]
> Can I use this module without root? With magisk the module tab is not active when my phone is not rooted. Is there other way (maybe via recovery mode or on Xiaomi phones with the fastboot mode) to inject this code into my system? I tried on Android 13 (Evolution X 7.5 ROM) with the latest magisk.

No is not possible without root. You need root for it.

**Comment by humarci** [comment]
But in the how to use:
"Open Call Recorder, modify settings as desired (you might want to leave "Recording Source" on "Auto"; there's NO need to use root (for "System Mixer Incall Recording") in the app)."

Maybe after the install the zip and remove the root, the modification still will be in part of the system?

**Comment by Hot12345** [comment]
> But in the how to use: "Open Call Recorder, modify settings as desired (you might want to leave "Recording Source" on "Auto"; there's NO need to use root (for "System Mixer Incall Recording") in the app)."
> 
> Maybe after the install the zip and remove the root, the modification still will be in part of the system?

Did you try it? And did it worked out?

**Comment by humarci** [comment]
> But in the how to use: "Open Call Recorder, modify settings as desired (you might want to leave "Recording Source" on "Auto"; there's NO need to use root (for "System Mixer Incall Recording") in the app)."

> Maybe after the install the zip and remove the root, the modification still will be in part of the system?

No, because I had to set everything again on the phone and it took almost a day.
Maybe next time.

**Comment by di72nn** [comment]
To use Magisk modules you need Magisk to be **installed**, that is, it should be a part of the boot image (or whatever image, if it is a non-standard installation).

You don't need the **Superuser / root access for the apps** enabled to use this particular module.

Please explain in more detail what exactly is your problem with Magisk if you're still struggling with this (though I'm not sure I'll be able to help).

You can also try to use [the app](https://gitlab.com/axet/android-call-recorder) without Magisk or root at all, it's just the app will be limited in permissions and most (or all) recording options may not work.
