### ISSUE TITLE
Callrecording doesnt work propperly anymore, Android 13 Latest security patch 5 februari 2023

### ISSUE THREAD

**Issue by Hot12345** [di72nn/callrecorder-axet#21]
Hi Axet,
I have problems with the call recording app (root)...

Im using the Xiaomi mi 11 pro, with root.
Android 13 Google security patch 5 Februari 2023.

My callrecording app; doesnt record sound anymore. I hear only a blip/crack sound and that is only thing what I hear.
I want that you debugg this issue with me.. Because before the security update everthing was working fine without any problems.

I installed the module from Github. I use only this module as root, no other modules being installed.
removed and reinstalled the module and started again and still not working..

If I wanna share a audio clip, it doesnt record anything, because there are no wave spikes, sounds. It something happend in the security patch of Android/Google.

Can you help me with this?

Kind Regards,

**Comment by Catfriend1** [comment]
I think this is the right place : https://gitlab.com/axet/android-call-recorder/-/issues

**Comment by Hot12345** [comment]
Case logged.
https://gitlab.com/axet/android-call-recorder/-/issues/217

**Comment by X4mro** [comment]
> Sprawa zarejestrowana. [https://gitlab.com/axet/android-call-recorder/-/issues/217 ](https://gitlab.com/axet/android-call-recorder/-/issues/217)

Try via Call Recorder apps (Version 1.8.2 (223) - Added on 2022-03-10 )

**Comment by Hot12345** [comment]
> > Sprawa zarejestrowana. [https://gitlab.com/axet/android-call-recorder/-/issues/217 ](https://gitlab.com/axet/android-call-recorder/-/issues/217)
> 
> Try via Call Recorder apps (Version 1.8.2 (223) - Added on 2022-03-10 )

Nope, also not working. Tried with different phones.
Currently running Oneplus 8 Pro. Xiaomi Mi 11 Pro tried, also not working on the latest Android update.
Before this update, it was able, possible to record phone calls, on default settings.
So the record-app, settings need to rework.
If I look for the phone-recording call skvalex,
"
It looks like Google just did some minor modifications to the code, so I had to make the app compatible with these modifications. Nothing to worry about, I don't think they'll break it again when the stable version is released.
No relation to root gaining issue.
"
Source: https://forum.xda-developers.com/t/android-4-0-call-recorder-skvalex-record-phone-calls-from-the-phone-line.1441643/post-87999863
So Google changed something in their code.
So fix, update yours app.

**Comment by di72nn** [comment]
Closing as this is not a module issue.

**Comment by Hot12345** [comment]
> Closing as this is not a module issue.

Why is this being closed and not a module issue? 
The module needs to be updated to the latest Android 13> security fix.

**Comment by di72nn** [comment]
The aforementioned skvalex call recorder was updated only on the app, not module side. I'm **not axet** and this is a Magisk **module** repo.

**Comment by Hot12345** [comment]
> 

Im not talking about skvalex call recorder, im just saying as a example, that it also get's broken after the Android 13 Google security patch on 5 Februari 2023. 

The call recording app Version 1.0.1 is not working anymore of the Axet's call recording. Its get broken. 
So the module (this) needs an update for the Android 13 Google security patch 5 Februari 2023.

**Comment by di72nn** [comment]
I mentioned skvalex call recorder only to point out that only the app needs to be updated, not the system config provided by the module. When the app update is published, it can simply be installed on the device as an update, without updating the module.
