### ISSUE TITLE
Ask before saving the recording

### ISSUE THREAD

**Issue by irfaniglesias** [di72nn/callrecorder-axet#4]
First of all, thanks for this wonderful software. I'm able to record my office calls on Android 10 which was not possible earlier.

I have one request. Can you please add an option to ask whether to save the recording or delete it despite the call duration.

It asks when the call is of 0 seconds but it still records calls of 1 second.

If you can update this, it will be really helpful

**Comment by di72nn** [comment]
I only created the Magisk module, the app itself is created by [axet](https://gitlab.com/axet). You should create an issue in the app repo: [axet/android-call-recorder](https://gitlab.com/axet/android-call-recorder).
