### ISSUE TITLE
Changing of cooding wont switch fileext in nameformat

### ISSUE THREAD

**Issue by NoGAD-de** [di72nn/callrecorder-axet#5]
Hello, if im switching from cooding wav to ogg, the name format ist still on wav. The file is really large.

This is an annoying bug?

Version: 1.0.1

**Comment by di72nn** [comment]
How many encoding options do you see in the list?

**Comment by NoGAD-de** [comment]
There are 8 options.
![Screenshot_20201127-194632_Call Recorder](https://user-images.githubusercontent.com/63698846/100477683-58303680-30e9-11eb-8582-4a5c049701f6.png)

**Comment by di72nn** [comment]
> the name format ist still on wav

Do you mean the option "Name Format"? The examples there don't have to change.

Are you sure the files are recorded in wav? Have you tried switching "encoding" to other formats?

**Comment by NoGAD-de** [comment]
Yes, i did switched to other formats. The caption of "Name Format" didnt changed.

Curiously on my own S9+ the Option ist on ogg, wont switch to another. On my mums Phone its locked on wav.
And yes, the files are recorded in wav format - really huges files.

![Screenshot_20201129-023138_Call Recorder](https://user-images.githubusercontent.com/63698846/100529790-24d5d080-31eb-11eb-9c0c-b6c290b3a2b7.png)

**Comment by di72nn** [comment]
Doesn't seem like it has anything to do with the magisk module. Try [the app repo](https://gitlab.com/axet/android-call-recorder).
